name: Build Tauri Project

on: [ push, pull_request ]  # 触发条件，可以是 push、pull_request 或者其他事件

jobs:
  build:
    name: Build Tauri App
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 检出代码仓库
      - name: Set environment for noninteractive
        run: |
          echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV

      - name: Install Build Dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: JonasKruckenberg/tauri-build@v1
        id: tauri_build